In [7]:
from DiSuQ.Torch.models import shuntedQubit,transmon,fluxonium
from DiSuQ.Torch.circuit import hamiltonianEnergy,Kerman,Charge,Flux,Oscillator
import torch,numpy
from numpy import around
from torch import tensor

## Fluxonium

#### charge basis

In [2]:
circuit = fluxonium(Charge,[50],sparse = False)
phi = tensor(.5)

In [3]:
H_LC = circuit.hamiltonianLC()
H_J = circuit.hamiltonianJosephson({'I':phi})

In [4]:
H = H_LC + H_J
hamiltonianEnergy(H)[:3]

tensor([-18.0253, -14.1280, -10.3371], dtype=torch.float64,
       grad_fn=<SliceBackward0>)

#### flux basis

In [2]:
circuit = fluxonium(Charge,[50],sparse = False)
phi = tensor(.5)

In [5]:
H_LC = circuit.fluxHamiltonianLC()
H_J = circuit.josephsonFlux({'I':phi})

AttributeError: 'Charge' object has no attribute 'fluxHamiltonianLC'

In [6]:
H = H_LC + H_J
hamiltonianEnergy(H)[:3]

tensor([ -0.4995, 399.8980, 400.3994], grad_fn=<SliceBackward0>)

#### oscillator basis

In [2]:
circuit = fluxonium(Charge,[50],sparse = False)
phi = tensor(.5)

In [7]:
H_LC = circuit.oscillatorHamiltonianLC()
H_J = circuit.josephsonOscillator({'I':phi})

In [8]:
H = H_LC + H_J
hamiltonianEnergy(H)[:3]

tensor([-13.7407, -13.7188,  -6.7796], grad_fn=<SliceBackward0>)

#### kerman basis

In [2]:
circuit = fluxonium(Charge,[50],sparse = False)
phi = tensor(.5)

In [9]:
basis = {'O':[50],'I':[],'J':[]}
circuit = fluxonium(basis,sparse=False)

In [10]:
H_LC = circuit.kermanHamiltonianLC()
H_J = circuit.kermanHamiltonianJosephson({'I':phi})

In [11]:
H = H_LC + H_J
hamiltonianEnergy(H)[:3]

tensor([-13.7407, -13.7188,  -6.7796], grad_fn=<SliceBackward0>)

# Transmon

In [12]:
basis = [100]
Ej,Ec = 20,.3
circuit = transmon(basis,Ej,Ec)

In [13]:
H_LC = circuit.chargeHamiltonianLC()
H_J = circuit.josephsonCharge({})
H = H_LC + H_J
H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([-16.6126,  -9.9992,  -3.7226], grad_fn=<SliceBackward0>)

#### basis : kerman/charge

In [14]:
basis = {'O':[],'I':[],'J':[100]}
circuit = transmon(basis,Ej,Ec,sparse=True)

In [15]:
H_LC = circuit.kermanHamiltonianLC()
H_J = circuit.kermanHamiltonianJosephson({})
H = H_LC + H_J
H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([-16.6113,  -9.9989,  -3.7234], grad_fn=<SliceBackward0>)

In [16]:
H_LC.to_dense()

tensor([[12000.0000+0.j,     0.0000+0.j,     0.0000+0.j,  ...,     0.0000+0.j,
             0.0000+0.j,     0.0000+0.j],
        [    0.0000+0.j, 11761.2002+0.j,     0.0000+0.j,  ...,     0.0000+0.j,
             0.0000+0.j,     0.0000+0.j],
        [    0.0000+0.j,     0.0000+0.j, 11524.8008+0.j,  ...,     0.0000+0.j,
             0.0000+0.j,     0.0000+0.j],
        ...,
        [    0.0000+0.j,     0.0000+0.j,     0.0000+0.j,  ..., 11524.8008+0.j,
             0.0000+0.j,     0.0000+0.j],
        [    0.0000+0.j,     0.0000+0.j,     0.0000+0.j,  ...,     0.0000+0.j,
         11761.2002+0.j,     0.0000+0.j],
        [    0.0000+0.j,     0.0000+0.j,     0.0000+0.j,  ...,     0.0000+0.j,
             0.0000+0.j, 12000.0000+0.j]], grad_fn=<ToDenseBackward0>)

In [17]:
around(H_J.detach().to_dense(),2)

tensor([[  0.-0.j, -10.+0.j,   0.+0.j,  ...,   0.-0.j,  -0.-0.j, -10.-0.j],
        [-10.-0.j,  -0.-0.j, -10.+0.j,  ...,   0.+0.j,  -0.+0.j,  -0.-0.j],
        [  0.-0.j, -10.-0.j,  -0.-0.j,  ...,  -0.-0.j,   0.+0.j,   0.-0.j],
        ...,
        [  0.+0.j,   0.-0.j,  -0.+0.j,  ...,  -0.+0.j, -10.+0.j,   0.+0.j],
        [ -0.+0.j,  -0.-0.j,   0.-0.j,  ..., -10.-0.j,  -0.+0.j, -10.+0.j],
        [-10.+0.j,  -0.+0.j,   0.+0.j,  ...,   0.-0.j, -10.-0.j,   0.+0.j]])

# C-shunted

#### basis : kerman / charge

In [18]:
circuit_charge = shuntedQubit([3,2,2],sparse=False)
phi = .0

In [19]:
H_LC = circuit_charge.chargeHamiltonianLC()
H_J = circuit_charge.josephsonCharge({'I':tensor(phi)})

In [20]:
H = H_LC + H_J

In [21]:
#H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([ -0.4096, 399.6755, 399.7998], grad_fn=<SliceBackward0>)

In [22]:
basis = {'O':[4],'I':[],'J':[2,2]}
circuit_kerman = shuntedQubit(basis,sparse=False)

In [23]:
H_LC = circuit_kerman.kermanHamiltonianLC()
H_J = circuit_kerman.kermanHamiltonianJosephson({'I':tensor(phi)})

In [24]:
H = H_LC + H_J

In [25]:
#H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([0.0794, 0.8799, 0.8819], grad_fn=<SliceBackward0>)

### backend : dense/sparse

In [26]:
basis = {'O':[4],'I':[],'J':[2,2]}

In [27]:
circuit_dense = shuntedQubit(basis,sparse=False)

In [28]:
H_LC = circuit_dense.kermanHamiltonianLC()
H_J = circuit_dense.kermanHamiltonianJosephson({'I':tensor(.125)})

In [29]:
H = H_LC + H_J

In [30]:
#H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([0.0808, 0.8763, 0.8776], grad_fn=<SliceBackward0>)

In [31]:
circuit_sparse = shuntedQubit(basis,sparse=True)

In [32]:
H_LC = circuit_sparse.kermanHamiltonianLC()
H_J = circuit_sparse.kermanHamiltonianJosephson({'I':tensor(.125)})

In [33]:
H = H_LC + H_J

In [34]:
H = H.to_dense()
hamiltonianEnergy(H)[:3]

tensor([0.0786, 0.8780, 0.8840], grad_fn=<SliceBackward0>)