In [1]:
from DiSuQ.Torch.dense import *
from torch import tensor
from torch.linalg import eigvalsh

In [2]:
N = 11
Z = tensor(1.)

In [3]:
Qo = basisQo(N,Z)
Fo = basisFo(N,Z)
print(eigvalsh(Qo))
print(eigvalsh(Fo))

tensor([-2.0697e+00, -1.5703e+00, -1.1430e+00, -7.4843e-01, -3.7057e-01,
         6.5283e-09,  3.7057e-01,  7.4843e-01,  1.1430e+00,  1.5703e+00,
         2.0697e+00])
tensor([-2.0697e+00, -1.5703e+00, -1.1430e+00, -7.4843e-01, -3.7057e-01,
         6.5283e-09,  3.7057e-01,  7.4843e-01,  1.1430e+00,  1.5703e+00,
         2.0697e+00])


In [4]:
Qq = basisQq(N)
Fq = basisFq(N)
print(eigvalsh(Qq))
print(eigvalsh(Fq))

tensor([-22., -20., -18., -16., -14., -12., -10.,  -8.,  -6.,  -4.,  -2.,   0.,
          2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.])
tensor([-5.3523e-05, -6.0916e-12, -1.3870e-12, -1.2335e-12, -9.6400e-13,
        -6.4956e-13, -4.3146e-13, -3.5961e-13, -2.2145e-13, -1.1991e-13,
        -6.0387e-14,  1.1552e-14,  6.7500e-14,  1.1048e-13,  2.8535e-13,
         3.8433e-13,  4.0868e-13,  6.1480e-13,  9.8462e-13,  1.2615e-12,
         1.4405e-12,  8.4816e-12,  5.3675e-05])


In [8]:
Ff = basisFf(N)
Qf = basisQf(N)
print(eigvalsh(Qf))
print(eigvalsh(Ff))

tensor([-5.9855e-01, -1.9605e-01, -1.2097e-06, -3.8285e-08, -1.9314e-08,
         4.0374e-10,  6.2434e-09,  2.1937e-08,  1.2116e-06,  1.9605e-01,
         5.9855e-01])
tensor([-1.0000, -0.8000, -0.6000, -0.4000, -0.2000,  0.0000,  0.2000,  0.4000,
         0.6000,  0.8000,  1.0000])


In [6]:
Ff.shape

torch.Size([11, 11])