## Mode-Basis analysis

In [2]:
import numpy,utils,sys,plotly,scipy
import plotly.offline as py
import plotly.graph_objs as go
from numpy.linalg import norm, matrix_rank as ra
from plotly.offline import init_notebook_mode
from circuit import Circuit, hamiltonianEnergy, phase
from components import *
import models
from copy import copy,deepcopy
from numpy.linalg import norm, inv, matrix_rank as rank
from numpy import abs,real,imag,around
#numpy.set_printoptions(precision=2)

init_notebook_mode(connected=True)
get_ipython().run_line_magic('matplotlib', 'inline')

In [15]:
from numpy import kron

In [27]:
Q = basisQq(3).real
I = identity(7).real

In [28]:
kron(Q,Q)

array([[36.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 24.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 12., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 12., -0., -0.],
       [ 0.,  0.,  0., ..., -0., 24., -0.],
       [ 0.,  0.,  0., ..., -0., -0., 36.]])

In [29]:
kron(Q@Q,I)

array([[36.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 36.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 36., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 36.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., 36.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., 36.]])

In [30]:
Q@Q

array([[36.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 16.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 16.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 36.]])

In [31]:
Q

array([[ 6.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -4.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -6.]])

### LC oscillator

In [10]:
circuit = models.oscillatorLC([100])

In [11]:
oscillator = circuit.circuitEnergy(H_LC=circuit.oscillatorHamiltonianLC(),exclude=True)
fluxed = circuit.circuitEnergy(H_LC=circuit.fluxHamiltonianLC(),exclude=True)
charged = circuit.circuitEnergy(H_LC=circuit.chargeHamiltonianLC(),exclude=True)
circuit.basis = {'O':[100],'I':[],'J':[]}
kerman = circuit.circuitEnergy(H_LC=circuit.kermanHamiltonianLC(),exclude=True)
utils.plotCompare(numpy.arange(len(oscillator)),{'oscillator':oscillator,'flux':fluxed,'kerman':kerman,'charge':charged})

### LC network

In [12]:
circuit = [L(0,1,.0001),C(0,1,100)]
circuit += [L(1,2,.0001),C(1,2,500)]
circuit += [L(2,3,.005)]
circuit += [L(3,4,.0005),C(3,4,600)]
circuit += [L(2,4,.0006),C(2,4,200)]
circuit += [L(4,5,.0003),C(4,5,150)]
circuit += [L(1,5,.0001),C(1,5,500)]

In [13]:
bases = [2,2,2,2,2]
circuit = Circuit(circuit,bases)

In [14]:
oscillator = circuit.circuitEnergy(H_LC=circuit.oscillatorHamiltonianLC(),H_J=circuit.josephsonOscillator,exclude=True)
fluxed = circuit.circuitEnergy(H_LC=circuit.fluxHamiltonianLC(),H_J=circuit.josephsonCharge,exclude=True)
kerman = circuit.circuitEnergy(H_LC=circuit.kermanHamiltonianLC(),H_J=circuit.josephsonCharge,exclude=True)
charged = circuit.circuitEnergy(H_LC=circuit.chargeHamiltonianLC(),H_J=circuit.josephsonCharge,exclude=True)
utils.plotCompare(numpy.arange(len(oscillator)),{'oscillator':oscillator,'flux':fluxed,'kerman':kerman,'charge':charged})

KeyboardInterrupt: 

For the same truncation size, oscillator basis has better response compared to charged(Kerman) basis. \
While the similarity between the two goes midway for smaller circuits like LC oscillator; \
it fails quite at the lowest levels for complex LC networks.